This code was completely messed up; found by accidence. Details below:
Background: I removed a return value in storm/include/storm/return_values.h. Then I started getting compilation errors like this:

main.c:258:13: error: duplicate case value
main.c:249:13: error: previously used here

The errors were rather strange since I hadn't done any modification to the main.c file! So I started looking at it. It turned out I was using completely bogus values here when checking the return values (C:s lack of "true" strict typing a la Java or C# comes to mind...). Because of this, and the fact that the enums had now changed values, I started getting these compile-time errors.

The first return value (STORM_RETURN_UNALIGNED_SECTION) was never ever returned from the called method (in elf.c). The second (STORM_RETURN_SUCCESS) just "happened" to be the same as RETURN_SUCCESS but I fixed it to be right now anyway.